### ISSUE TITLE
error on windows "No module named:structLog"

### ISSUE THREAD

**Issue by BoladoSeis** [dvf/blockchain-book#1]
This is the error i get when I put: python node.py:
Traceback (most recent call last):
  File "C:\Users\marce\blockchain-book\chapters\chapter_7\node.py", line 3, in <module>
    from funcoin.blockchain import Blockchain
  File "C:\Users\marce\blockchain-book\chapters\chapter_7\funcoin\blockchain.py", line 8, in <module>
    import structlog
ModuleNotFoundError: No module named 'structlog'

**Comment by nopressurecooker** [comment]
I get the same error running on Macintosh.

**Comment by doneforaiur** [comment]
Did you followed the instructions?
`cd chapters/chapter_7`
`poetry install`

If the issue persists, you can always manually install libraries like this; 
`pip install structlog`
